# folder settings
source: .
destination: ./_site

# site settings
permalink: /:categories/:title
# site url
url: zv.github.com 

# Site settings
full-name: Zephyr Pellerin
title: A new kind of sentience
email: zv@nxvr.org
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: zefyear
github_username:  zv

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass

include:
  - commentary.html

gems:
  - jekyll-sitemap

# exclude files for generated site
exclude: 
- org/
- README.md
- LICENSE
- Rakefile
- nite.tmproj

